// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var newtext;
    newtext = $('<p>New text</p>');
    return $('button').on('click', function() {
      return newtext.appendTo('#box3');
    });
  });

}).call(this);

/*
//@ sourceMappingURL=application.map
*/
