// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var newtext;
    newtext = $('<p>New text</p>');
    return $('button').on('click', function() {
      return newtext.appendTo('#box3');
    });
  });

  $(function() {
    var initialize, logging, mouseevents;
    $('#log').draggable();
    logging = function(content) {
      return $('#log').append(content);
    };
    initialize = function(insert) {
      var row;
      row = $("<tr><td>" + insert + "</td><td class='" + insert + "'></td></tr>");
      row.appendTo('#box1 table');
      return $('#area').on(insert, function() {
        $('#box1').find("td").removeClass('green');
        return $('#box1').find("." + insert).addClass('green');
      });
    };
    mouseevents = ['click', 'dblclick', 'focusin', 'focusout', 'mousedown', 'mouseup', 'mousemove', 'mouseout', 'mouseover', 'mouseleave', 'mouseenter'];
    return mouseevents.forEach(initialize);
  });

  $(function() {
    return $('.confirmation').on('click', 'button', function() {
      return $.ajax('forajax/confirmation.php', {
        success: function(response) {
          return $('.ticket').html(response).slideDown();
        },
        data: {
          'confNum': $('.ticket').data('confirm')
        },
        error: function(request, errorType, errorMessage) {
          return alert('Request: ' + request + ', Error: ' + errorType + ', Message: ' + errorMessage);
        },
        timeout: 3000,
        beforeSend: function() {
          return $('.confirmation').addClass('is-loading');
        },
        complete: function() {
          return $('.confirmation').removeClass('is-loading');
        }
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=application.map
*/
