source 'http://rubygems.org'

gem "middleman", "~>3.1.5"
gem "middleman-livereload", "~> 3.1.0"
gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]

gem 'middleman-ember', github: "nerdyworm/middleman-ember"
gem 'coffee-script', require: false
gem 'handlebars_assets', require: false