// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var TodoItem, TodoView, todoItem;
    TodoItem = Backbone.Model.extend();
    TodoView = Backbone.View.extend();
    todoItem = new TodoItem({
      description: 'Pick up milk',
      status: 'incomplete'
    });
    return $('body').on('click', function() {
      return console.log(this);
    });
  });

}).call(this);
