// Generated by CoffeeScript 1.6.3
$(function() {
  var TodoItem, TodoView, todoItem;
  TodoItem = Backbone.Model.extend({});
  TodoView = Backbone.View.extend({});
  return todoItem = new TodoItem({
    description: 'Pick up milk',
    status: 'incomplete'
  });
});
