// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    $('#download').on('click', function() {
      return $.getJSON('forajax/genjson.php', function(data) {
        var insertThis;
        insertThis = $.map(data, function(row, index) {
          var listItem;
          listItem = $("<li></li>");
          $('<h3>' + row.name + '</h3>').appendTo(listItem);
          $('<p>' + row.status + '</p>').appendTo(listItem);
          return listItem;
        });
        return $('#inserthere').hide().html(insertThis).fadeIn();
      });
    });
    return $('#flickr_button').on('click', function() {
      return $.getJSON('http://api.flickr.com/services/feeds/photos_public.gne?jsoncallback=?', {
        tags: $('#search').val(),
        tagmode: 'any',
        format: 'json'
      }, function(data) {
        return $.each(data.items, function(i, item) {
          $('<img/>').attr('src', item.media.m).appendTo('#images');
          if (i === 100) {
            return false;
          }
        });
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=tryjson.map
*/
