source "https://rubygems.org"

gem "middleman", "~>3.1.6"
gem 'json', '~> 1.7.7'
gem "middleman-livereload"
gem 'ember-source', '~>1.0.0'
gem 'handlebars_assets'
gem 'ember-data-source'
gem "middleman-emblem", "~> 1.1.1"
gem 'bootstrap-sass', github: 'thomas-mcdonald/bootstrap-sass', branch: '3', :require => false
gem 'middleman-emberscript', '~> 1.0.0'

group :development do
  gem 'puma'
end